# Generated by Django 2.2.10 on 2021-09-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_stockinfo_stockpricebydate_stockpricegroup_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockpricebydate',
            name='group_id',
        ),
        migrations.AddField(
            model_name='stockpricebydate',
            name='type',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='StockPriceGroup',
        ),
    ]
