# Generated by Django 2.2.10 on 2021-09-12 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210912_2052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
