# Generated by Django 2.2.10 on 2021-09-12 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockinfo',
            options={'ordering': ['ticket']},
        ),
        migrations.RenameField(
            model_name='stockinfo',
            old_name='ticker',
            new_name='ticket',
        ),
    ]
