# Generated by Django 2.2.10 on 2021-09-14 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210913_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinfo',
            name='dividend',
        ),
        migrations.AddField(
            model_name='order',
            name='max_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='min_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ticket_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_info_id', to='orders.StockInfo'),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='is_forecast',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_name',
            field=models.CharField(max_length=5),
        ),
        migrations.DeleteModel(
            name='StockPriceByDate',
        ),
    ]
