# Generated by Django 2.2.10 on 2021-09-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210914_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinfo',
            name='is_forecast',
        ),
        migrations.RemoveField(
            model_name='stockinfo',
            name='market_capitalization',
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='source',
            field=models.TextField(null=True),
        ),
    ]
